version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service_account.json
      - BIGQUERY_DATASET=your_dataset
