version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DBT_PROFILES_DIR=/app/fetch_coding_challenge
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service_account.json
      - BIGQUERY_DATASET=fetch_data
